window.FOREIGN_WORDS = [
  { word: "MENU", definition: "Spis potraw i napojów oferowanych np. w restauracji." },
  { word: "ETUI", definition: "Pokrowiec ochronny na mały przedmiot, np. okulary lub telefon." },
  { word: "JAZZ", definition: "Gatunek muzyki wywodzący się z kultury afroamerykańskiej." },
  { word: "BOSS", definition: "Potoczne określenie szefa lub przełożonego." },
  { word: "LIFT", definition: "Urządzenie dźwigowe; w użyciu międzynarodowym odpowiednik windy." },
  { word: "SHOW", definition: "Widowisko lub występ przygotowany dla publiczności." },
  { word: "TEAM", definition: "Zespół ludzi pracujących wspólnie nad zadaniem." },
  { word: "MAIL", definition: "Wiadomość elektroniczna przesyłana przez internet." },
  { word: "RING", definition: "Okrąg lub arena walk sportowych, zwłaszcza bokserskich." },
  { word: "QUIZ", definition: "Krótki test wiedzy, zwykle w formie pytań i odpowiedzi." },
  { word: "DEAL", definition: "Umowa handlowa, porozumienie biznesowe." },
  { word: "BLOG", definition: "Internetowy dziennik publikowany regularnie przez autora." },
  { word: "GOLF", definition: "Sport polegający na umieszczeniu piłki w dołku jak najmniejszą liczbą uderzeń." },
  { word: "CAMP", definition: "Obóz, zwykle tymczasowe miejsce pobytu." },
  { word: "CHAT", definition: "Rozmowa tekstowa prowadzona online." },
  { word: "TEST", definition: "Sprawdzian wiedzy, umiejętności lub działania systemu." },
  { word: "TOKEN", definition: "Jednostka dostępu lub autoryzacji w systemach informatycznych." },
  { word: "TREND", definition: "Kierunek zmian, moda lub dominująca tendencja." },
  { word: "BONUS", definition: "Dodatkowe świadczenie, nagroda lub korzyść." },
  { word: "LOGIN", definition: "Nazwa użytkownika służąca do logowania." },
  { word: "RESET", definition: "Przywrócenie stanu początkowego urządzenia lub systemu." },
  { word: "COACH", definition: "Trener wspierający rozwój i osiąganie celów." },
  { word: "HOTEL", definition: "Obiekt noclegowy oferujący pokoje i usługi dla gości." },
  { word: "LASER", definition: "Urządzenie emitujące silnie skupioną wiązkę światła." },
  { word: "HOBBY", definition: "Ulubione zajęcie wykonywane w czasie wolnym." },
  { word: "PIZZA", definition: "Danie kuchni włoskiej z ciasta i dodatków." },
  { word: "MOTTO", definition: "Krótka dewiza wyrażająca ideę lub zasadę." },
  { word: "RADAR", definition: "System wykrywania obiektów za pomocą fal radiowych." },
  { word: "LIDER", definition: "Osoba prowadząca grupę lub wyznaczająca kierunek działań." },
  { word: "PANEL", definition: "Zestaw elementów sterujących lub część dyskusyjna konferencji." },
  { word: "PATCH", definition: "Poprawka oprogramowania usuwająca błędy." },
  { word: "DRAFT", definition: "Wersja robocza dokumentu lub projektu." },
  { word: "FORUM", definition: "Miejsce wymiany opinii, dziś często w formie internetowej." },
  { word: "VIDEO", definition: "Materiał filmowy zapisany cyfrowo." },
  { word: "EMAIL", definition: "Poczta elektroniczna lub pojedyncza wiadomość e-mail." },
  { word: "SERWER", definition: "Komputer lub usługa udostępniająca dane innym urządzeniom." },
  { word: "FORMAT", definition: "Ustalona forma zapisu danych lub struktury treści." },
  { word: "KURSOR", definition: "Wskaźnik pozycji na ekranie komputera." },
  { word: "PORTAL", definition: "Rozbudowany serwis internetowy łączący różne usługi." },
  { word: "BUDŻET", definition: "Plan dochodów i wydatków na określony okres." },
  { word: "KLIENT", definition: "Osoba lub firma korzystająca z usług albo kupująca produkty." },
  { word: "SYSTEM", definition: "Powiązany układ elementów działających według zasad." },
  { word: "STYLUS", definition: "Rysik do obsługi ekranów dotykowych." },
  { word: "MANUAL", definition: "Instrukcja obsługi lub podręcznik użytkownika." },
  { word: "PROFIL", definition: "Zestaw informacji opisujących osobę, firmę lub ustawienia." },
  { word: "SEKTOR", definition: "Wydzielona część gospodarki, rynku lub przestrzeni." },
  { word: "KAMERA", definition: "Urządzenie do rejestracji obrazu." },
  { word: "TABLET", definition: "Przenośne urządzenie z ekranem dotykowym." },
  { word: "GADŻET", definition: "Niewielki, praktyczny lub ozdobny przedmiot, często elektroniczny." },
  { word: "WEEKEND", definition: "Koniec tygodnia, zwykle sobota i niedziela." },
  { word: "MANAGER", definition: "Osoba zarządzająca zespołem, projektem lub firmą." },
  { word: "PARKING", definition: "Miejsce przeznaczone do postoju pojazdów." },
  { word: "RANKING", definition: "Uszeregowana lista wyników, ocen lub pozycji." },
  { word: "PODCAST", definition: "Audycja audio udostępniana w internecie." },
  { word: "PROGRAM", definition: "Plan działania lub zestaw instrukcji dla komputera." },
  { word: "KATALOG", definition: "Uporządkowany spis obiektów, produktów lub plików." },
  { word: "ANALIZA", definition: "Szczegółowe badanie zjawiska lub danych." },
  { word: "MONITOR", definition: "Ekran komputerowy lub system nadzorujący przebieg procesu." },
  { word: "TELEFON", definition: "Urządzenie do komunikacji głosowej i cyfrowej." },
  { word: "GALERIA", definition: "Przestrzeń wystawowa albo zbiór obrazów/zdjęć." },
  { word: "KARIERA", definition: "Przebieg życia zawodowego i kolejne etapy rozwoju." },
  { word: "KONTENT", definition: "Treść publikowana w mediach i internecie." }
];
